# Generated by Django 6.0.3 on 2026-03-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='customer_category',
            field=models.CharField(choices=[('NEW', 'New'), ('REGULAR', 'Regular'), ('VIP', 'VIP')], default='NEW', max_length=20),
        ),
    ]
