# Generated by Django 6.0.3 on 2026-03-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_customer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='job_description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer_category',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('CORPORATE', 'Corporate'), ('VIP', 'VIP')], max_length=20),
        ),
    ]
