# Generated by Django 6.0.3 on 2026-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_job_description_alter_quote_customer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindecision',
            name='admin_decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemrecommendation',
            name='generated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
