# Generated by Django 6.0.3 on 2026-03-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_admindecision_admin_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='size',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='SMALL', max_length=20, null=True),
        ),
    ]
