# Generated by Django 6.0.3 on 2026-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_quote_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='size',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=20, null=True),
        ),
    ]
