# Generated by Django 6.0.3 on 2026-03-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_address_customer_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='customers.customer'),
        ),
    ]
